### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sgr792** [XZot1K/PhysicsToGo#14]
[23:52:56 ERROR]: Could not pass event EntityExplodeEvent to PhysicsToGo v2.0.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:194) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:1877) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1227) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.EntityTNTPrimed.explode(EntityTNTPrimed.java:94) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.EntityTNTPrimed.B_(EntityTNTPrimed.java:74) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.IndexOutOfBoundsException: Index: 118, Size: 116
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_311]
        at java.util.ArrayList.remove(ArrayList.java:498) ~[?:1.8.0_311]
        at xzot1k.plugins.ptg.core.Listeners.onExplode(Listeners.java:239) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-ab13683]
        ... 17 more

-------------------------------------------------------------------------------
This is the problem with version 1.12.2. I tested spigot and mod server. They can only be used for explosion recovery

**Comment by Sgr792** [comment]
[04:22:15] [Server thread/ERROR]: Could not pass event BlockBreakEvent to PhysicsToGo v2.0.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:69) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1200) [CraftEventFactory.class:git-CatServer-1.12.2-6eb82ffe]
        at catserver.server.CatServerEventHandler.onBlockBreak(CatServerEventHandler.java:30) [CatServerEventHandler.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_85_CatServerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:835) [ForgeHooks.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:356) [or.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:304) [or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1112) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_311]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_311]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.NullPointerException
        at xzot1k.plugins.ptg.core.Listeners.onBreak(Listeners.java:176) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor33.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
        ... 23 more
		
		
		
[04:19:37] [Netty Server IO #3/ERROR]: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:121)
        io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:848)
        net.minecraft.network.PacketBuffer.readBytes(PacketBuffer.java:965)
        net.minecraft.network.play.client.CPacketCustomPayload.func_148837_a(CPacketCustomPayload.java:39)
        net.minecraft.network.NettyPacketDecoder.decode(SourceFile:40)
        sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:498)
        com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
        com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:490)
        io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
        io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        java.lang.Thread.run(Thread.java:748)
[04:19:38] [Server thread/ERROR]: Could not pass event BlockBreakEvent to PhysicsToGo v2.0.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:69) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1200) [CraftEventFactory.class:git-CatServer-1.12.2-6eb82ffe]
        at catserver.server.CatServerEventHandler.onBlockBreak(CatServerEventHandler.java:30) [CatServerEventHandler.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_85_CatServerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:835) [ForgeHooks.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:356) [or.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:304) [or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1112) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_311]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_311]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.NullPointerException
        at xzot1k.plugins.ptg.core.Listeners.onBreak(Listeners.java:176) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor33.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
        ... 23 more
