### ISSUE TITLE
[BUG] This is the problem with version 1.12.2. I tested spigot and mod server. They can only be used for explosion recovery

### ISSUE THREAD

**Issue by Sgr792** [XZot1K/PhysicsToGo#15]
[08:10:19] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to PhysicsToGo v2.0.5
java.lang.NoSuchMethodError: org.bukkit.event.block.BlockPhysicsEvent.getSourceBlock()Lorg/bukkit/block/Block;
        at xzot1k.plugins.ptg.core.Listeners.onFall(Listeners.java:61) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor3.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraft.world.World.func_190524_a(World.java:712) [amu.class:?]
        at net.minecraft.world.World.func_175685_c(World.java:654) [amu.class:?]
        at net.minecraft.world.World.func_175722_b(World.java:598) [amu.class:?]
        at net.minecraft.world.World.markAndNotifyBlock(World.java:536) [amu.class:?]
        at net.minecraft.world.World.func_180501_a(World.java:515) [amu.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:163) [CraftBlock.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:194) [CraftBlockState.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:177) [CraftBlockState.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:58) [arb.class:?]
        at net.minecraft.block.Block.func_180645_a(Block.java:508) [aow.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:605) [oo.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:331) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
[08:10:19] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to PhysicsToGo v2.0.5
java.lang.NoSuchMethodError: org.bukkit.event.block.BlockPhysicsEvent.getSourceBlock()Lorg/bukkit/block/Block;
        at xzot1k.plugins.ptg.core.Listeners.onFall(Listeners.java:61) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor3.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraft.world.World.func_190524_a(World.java:712) [amu.class:?]
        at net.minecraft.world.World.func_175685_c(World.java:655) [amu.class:?]
        at net.minecraft.world.World.func_175722_b(World.java:598) [amu.class:?]
        at net.minecraft.world.World.markAndNotifyBlock(World.java:536) [amu.class:?]
        at net.minecraft.world.World.func_180501_a(World.java:515) [amu.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:163) [CraftBlock.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:194) [CraftBlockState.class:git-CatServer-1.12.2-6eb82ffe]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:177) [CraftBlockState.class:git-CatServer-1.12.2-6eb82ffe]
        at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:58) [arb.class:?]
        at net.minecraft.block.Block.func_180645_a(Block.java:508) [aow.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:605) [oo.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:331) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]

**Comment by XZot1K** [comment]
> [08:10:19] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to PhysicsToGo v2.0.5 java.lang.NoSuchMethodError: org.bukkit.event.block.BlockPhysicsEvent.getSourceBlock()Lorg/bukkit/block/Block; at xzot1k.plugins.ptg.core.Listeners.onFall(Listeners.java:61) ~[?:?] at catserver.server.executor.asm.generated.GeneratedEventExecutor3.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe] at net.minecraft.world.World.func_190524_a(World.java:712) [amu.class:?] at net.minecraft.world.World.func_175685_c(World.java:654) [amu.class:?] at net.minecraft.world.World.func_175722_b(World.java:598) [amu.class:?] at net.minecraft.world.World.markAndNotifyBlock(World.java:536) [amu.class:?] at net.minecraft.world.World.func_180501_a(World.java:515) [amu.class:?] at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:163) [CraftBlock.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:194) [CraftBlockState.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:177) [CraftBlockState.class:git-CatServer-1.12.2-6eb82ffe] at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:58) [arb.class:?] at net.minecraft.block.Block.func_180645_a(Block.java:508) [aow.class:?] at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:605) [oo.class:?] at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:331) [oo.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311] [08:10:19] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to PhysicsToGo v2.0.5 java.lang.NoSuchMethodError: org.bukkit.event.block.BlockPhysicsEvent.getSourceBlock()Lorg/bukkit/block/Block; at xzot1k.plugins.ptg.core.Listeners.onFall(Listeners.java:61) ~[?:?] at catserver.server.executor.asm.generated.GeneratedEventExecutor3.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe] at net.minecraft.world.World.func_190524_a(World.java:712) [amu.class:?] at net.minecraft.world.World.func_175685_c(World.java:655) [amu.class:?] at net.minecraft.world.World.func_175722_b(World.java:598) [amu.class:?] at net.minecraft.world.World.markAndNotifyBlock(World.java:536) [amu.class:?] at net.minecraft.world.World.func_180501_a(World.java:515) [amu.class:?] at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:163) [CraftBlock.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:194) [CraftBlockState.class:git-CatServer-1.12.2-6eb82ffe] at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:177) [CraftBlockState.class:git-CatServer-1.12.2-6eb82ffe] at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:58) [arb.class:?] at net.minecraft.block.Block.func_180645_a(Block.java:508) [aow.class:?] at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:605) [oo.class:?] at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:331) [oo.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]

`* Added the ".iml" project file.`
`* Added a quick try/catch for older versions when handling "cancel-fall-radius" for the time being.`

Added this into the latest jar for the time being.
