### ISSUE TITLE
Towny exception

### ISSUE THREAD

**Issue by SlimeDog** [XZot1K/PhysicsToGo#2]
Spigot 1.13.2 latest
PhysicsToGo 1.7.6.8

On startup:
```
[13:11:28] [Server thread/INFO]: [PhysicsToGo] Enabling PhysicsToGo v1.7.6.8
[13:11:28] [Server thread/INFO]: ^[[0;33;22m^[[21mPTG^[[m ^[[0;37;22m- ^[[0;31;1mSetting up required requisites...^[[m
[13:11:28] [Server thread/ERROR]: Error occurred while enabling PhysicsToGo v1.7.6.8 (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/NotRegisteredException
        at XZot1K.plugins.ptg.PhysicsToGo.onEnable(PhysicsToGo.java:38) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.NotRegisteredException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.2.jar-2018-12-21-2107:git-Spigot-573cdf2-dff66df]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 12 more
```
In config.yml:
```
hooks-options:
...
  towny:
    # If this is enabled, physics to go features will not work within town blocks.
    use-towny: false
```

**Comment by timmyRS** [comment]
I'm having the same issue on Paper 1.13.2 using PhysicsToGo 1.7.6.9.

**Comment by SlimeDog** [comment]
Spigot 1.13.2 latest
PTG 1.7.6.9

Same issue as above.
```
[08:14:30] [Server thread/INFO]: [PhysicsToGo] Enabling PhysicsToGo v1.7.6.9
[08:14:30] [Server thread/INFO]: PTG - Setting up required requisites...
[08:14:30] [Server thread/ERROR]: Error occurred while enabling PhysicsToGo v1.7.6.9 (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/NotRegisteredException
        at XZot1K.plugins.ptg.PhysicsToGo.onEnable(PhysicsToGo.java:38) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.NotRegisteredException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 12 more
```

**Comment by timmyRS** [comment]
Fixed in the latest version.

**Comment by SlimeDog** [comment]
Agreed. Version 1.7.8.
